### ISSUE TITLE
Geojson is incomplete 

### ISSUE THREAD

**Issue by alexaca79** [MissHaltLHIN/MissHaltLHIN#2]
There is a missing CMA area in the centre of the LHIN. 
I discovered it while hovering over the low count areas.

**Comment by mi-lee** [comment]
<img width="502" alt="screen shot 2016-08-30 at 8 38 08 pm" src="https://cloud.githubusercontent.com/assets/8763950/18111945/b36ad500-6ef1-11e6-825d-437883326d52.png">

@mackeynichols
